export const cardArray = [
    {
        id: 0,
        title: 'Первый товра',
        price: '170 ₽',
        address: 'Казань, р-н Вахитовский',
        date: '10 июля 11:39',
        img: '/image/Card-img.png',
    },
    {
        id: 1,
        title: 'Второй товра',
        price: '171 ₽',
        address: 'Казань, р-н Вахитовский',
        date: '10 июля 11:39',
        img: '/image/Card-img.png',
    },
    {
        id: 2,
        title: 'Третий товра',
        price: '172 ₽',
        address: 'Казань, р-н Вахитовский',
        date: '10 июля 11:39',
        img: '/image/Card-img.png',
    },
    {
        id: 3,
        title: 'Четвертый товра',
        price: '173 ₽',
        address: 'Казань, р-н Вахитовский',
        date: '10 июля 11:39',
        img: '/image/Card-img.png',
    },
    {
        id: 4,
        title: 'Пятый товра',
        price: '174 ₽',
        address: 'Казань, р-н Вахитовский',
        date: '10 июля 11:39',
        img: '/image/Card-img.png',
    },
    {
        id: 5,
        title: 'Шестой товра',
        price: '175 ₽',
        address: 'Казань, р-н Вахитовский',
        date: '10 июля 11:39',
        img: '/image/Card-img.png',
    },
]